### ISSUE TITLE
Rotated Thai text in GD broken by commit 4de63dcaa6568f2864a36a6ef658d12e9c3012ac

### ISSUE THREAD

**Issue by andypoo** [HOST-Oman/libraqm#145] opened 2021-12-03 01:46 UTC
There is a regression when FT_Get_Transform is used that I noticed on Slackware from the move to FreeType 2.10.4 to 2.11.0 (thus this function becoming available).

When using GD to render Thai fonts on a 90 degree angle (sideways), then all characters get rendered at the same position.  Changing the code (whilst still using 2.11.0) to disable the HAVE_FT_GET_TRANSFORM codepath resolved the issue.

**Comment by khaledhosny** [comment] 2021-12-03 02:57
Duplicate of #141

**Closed by khaledhosny** 2021-12-03 02:57 UTC
