### ISSUE TITLE
Feature request - Line breaking

### ISSUE THREAD

**Issue by preet** [HOST-Oman/libraqm#57] opened 2016-03-24 18:52 UTC
It would be neat if libraqm supported line breaking. This would make it an all in one solution for basic text layout. Perhaps something like (https://github.com/adah1972/libunibreak) can be used?

**Comment by bakercp** [comment] 2016-03-24 18:53
+1 To this.  I'm currently using libunibreak and would love to see it integrated into libraqm!

**Comment by khaledhosny** [comment] 2016-03-24 21:33
@mzn723 is currently working on line breaking support.

**Comment by khaledhosny** [comment] 2016-04-04 11:05
We have #58 now, it would be nice if you can test it and report any issues you have.

**Comment by khaledhosny** [comment] 2016-08-14 13:57
Duplicate of #50.

**Closed by khaledhosny** 2016-08-14 13:57 UTC
